Fixing conflicting dependencies
The conflict is caused by:
    The user requested kubernetes==9.0.1
    jupyterhub-kubespawner 0.10.2.dev0 depends on kubernetes>=7.0
    openshift 0.10.0 depends on kubernetes~=10.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: Cannot install -r /tmp/src/requirements.txt (line 10), -r /tmp/src/requirements.txt (line 4) and kubernetes==9.0.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /tmp/scripts/assemble": exit status 1